/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import javax.swing.JFrame;

/**
 *
 * @author carlosabia
 */
public class VentanaProyecto extends javax.swing.JFrame {

    /**
     * Creates new form VentanaProyecto
     */
    public VentanaProyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAlberto = new javax.swing.JButton();
        botonMarco = new javax.swing.JButton();
        botonIgor = new javax.swing.JButton();
        botonRoberto = new javax.swing.JButton();
        botonCarlos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAlberto.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        botonAlberto.setForeground(new java.awt.Color(255, 0, 0));
        botonAlberto.setText("Alberto");
        botonAlberto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAlbertoMousePressed(evt);
            }
        });
        botonAlberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlbertoActionPerformed(evt);
            }
        });

        botonMarco.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        botonMarco.setForeground(new java.awt.Color(255, 0, 0));
        botonMarco.setText("Marco");
        botonMarco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonMarcoMousePressed(evt);
            }
        });

        botonIgor.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        botonIgor.setForeground(new java.awt.Color(255, 0, 0));
        botonIgor.setText("Igor");
        botonIgor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonIgorMousePressed(evt);
            }
        });

        botonRoberto.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        botonRoberto.setForeground(new java.awt.Color(255, 0, 0));
        botonRoberto.setText("Roberto");
        botonRoberto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonRobertoMousePressed(evt);
            }
        });

        botonCarlos.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        botonCarlos.setForeground(new java.awt.Color(255, 0, 0));
        botonCarlos.setText("Carlos");
        botonCarlos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCarlosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAlberto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMarco, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonCarlos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonRoberto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIgor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonAlberto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonIgor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonMarco, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRoberto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(botonCarlos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCarlosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCarlosMousePressed
        ClaseCarlos carlos = new ClaseCarlos();
        carlos.setVisible(true);
        carlos.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
    }//GEN-LAST:event_botonCarlosMousePressed

    private void botonAlbertoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAlbertoMousePressed
        ClaseAlberto alberto = new ClaseAlberto();
        alberto.setVisible(true);
        alberto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_botonAlbertoMousePressed

    private void botonMarcoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMarcoMousePressed
        ClaseMarco marco = new ClaseMarco();
        marco.setVisible(true);
        marco.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_botonMarcoMousePressed

    private void botonRobertoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRobertoMousePressed
        ClaseRoberto roberto = new ClaseRoberto();
        roberto.setVisible(true);
        roberto.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_botonRobertoMousePressed

    private void botonIgorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIgorMousePressed
        ClaseIgor igor = new ClaseIgor();
        igor.setVisible(true);
        igor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_botonIgorMousePressed

    private void botonAlbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlbertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAlbertoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaProyecto().setVisible(true);
                
                new ClaseCarlos().setVisible(false);
                new ClaseIgor().setVisible(false);
                new ClaseAlberto().setVisible(false);
                new ClaseMarco().setVisible(false);
                new ClaseRoberto().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlberto;
    private javax.swing.JButton botonCarlos;
    private javax.swing.JButton botonIgor;
    private javax.swing.JButton botonMarco;
    private javax.swing.JButton botonRoberto;
    // End of variables declaration//GEN-END:variables
}
